name: CalcAMP
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.7
  - catboost>=0.26
  - jupyter
  - matplotlib>=3.3.4
  - pandas>=1.2.3
  - matplotlib-venn>=0.11.6
  - numpy>=1.20.1
  - pycaret==2.3.6
  - scikit-learn>=0.23.2
  - scipy>=1.5.4
  - seaborn>=0.11.1
  - shap>=0.40.0
  - xgboost==1.5.0
  - modlamp


